#!/bin/bash
#
#   This utility checks whether deployer is csgteam for certain
#   escalated privilege scripts.
#
#   Last Revised:   09:14, 23 Feb 2023
#

my_user=$(whoami)

if [[ $my_user != csgteam ]]; then
    >&2 echo "Error: cannot modify public Conda envs as $my_user"
    exit 1
fi
