#!/bin/bash
#
#   This script installs a kernel for a specified version of Matlab
#

set -e

# Settings
my_dir="$( cd "$(dirname "$(readlink -f "$0")")" ; pwd )"
my_user=$(whoami)
ncarenv_version=$(module -t list |& grep ncarenv | cut -d/ -f2)
matlab_version=$(module -t list |& grep matlab | cut -d/ -f2)

if [[ -z $matlab_version ]]; then
    >&2 echo "Error: Please load desired Matlab module first!"
    exit 1
fi

if [[ " $@ " != *" --user "* ]]; then
    if [[ $my_user != csgteam ]]; then
        export kernel_prefix="ktest-"
    fi

    if [[ $CONDA_PREFIX != *jhk-* ]] && [[ $CONDA_PREFIX != *jhub-* ]]; then
        >&2 echo "Error: Please load a JupyterHub Kernel conda environment first!"
        exit 1
    fi
elif [[ -z $CONDA_PREFIX ]] || ! which jupyter-lab >& /dev/null; then
    >&2 echo "Error: Please load a Conda environment with JupyterLab first!"
    exit 1
else
    export kernel_prefix="user-"
fi

if ! pip list |& grep -q -e ^matlab-kernel; then
    >&2 echo "Error: conda environment must provide matlab_kernel package. Try:"
    >&2 echo -e "\n       conda install numpy ipython wurlitzer metakernel"
    >&2 echo -e "       pip install --no-cache-dir matlab_kernel\n"
    exit 1
fi

if [[ $my_user == csgteam ]]; then
    export hub_kernels_private=/glade/u/ssg/ch/usr/jupyterhub/kernels
    export hub_kernels_public=/glade/u/apps/jupyterhub/csg-managed/prod/kernels
else
    export hub_kernels_private=$HOME/.local/share/jupyter/kernels
fi

kernel_name=${kernel_prefix}matlab-${matlab_version,,}
kernel_file=$hub_kernels_private/$kernel_name/kernel.json

module -q purge
module -q load ncarenv/$ncarenv_version matlab/$matlab_version

# Install the system- and version-specific engine
# See https://pypi.org/project/matlabengine/#history for version mapping
declare -A me_map pv_map
me_map[R2024a]=24.1.*
me_map[R2023b]=23.2.*
me_map[R2023a]=9.14.*
me_map[R2022b]=9.13.*
me_map[R2022a]=9.12.*
me_map[R2021b]=9.11.*
me_map[R2021a]=9.10.*
me_map[R2020b]=9.9.*

pv_map[R2024a]="3.9 3.10 3.11"
pv_map[R2023b]="3.9 3.10 3.11"
pv_map[R2023a]="3.8 3.9 3.10"
pv_map[R2022b]="3.8 3.9 3.10"
pv_map[R2022a]="3.8 3.9"
pv_map[R2021b]="3.7 3.8 3.9"
pv_map[R2021a]="3.7 3.8"
pv_map[R2020b]="3.6 3.7 3.8"

function install_engine {
    export PYTHONPATH=$engine_prefix/lib/python${python_version}/site-packages:$PYTHONPATH
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NCAR_ROOT_MATLAB/bin/glnxa64

    pip install --no-cache-dir --prefix=$engine_prefix matlabengine==${me_map[$matlab_version]}
}

# Check Python-Matlab compatibility
python_version=$(python -c "import sys; print('{}.{}'.format(*sys.version_info[:2]))")

if [[ " ${pv_map[$matlab_version]} " != *" $python_version "* ]]; then
    >&2 echo "Error: This Matlab version ($matlab_version) cannot be used in an environment"
    >&2 echo "       with Python $python_version. Allowed Python versions include:"
    >&2 echo -e "\n       ${pv_map[$matlab_version]}\n"
    exit 1
fi

engine_prefix=$CONDA_PREFIX/kernel-packages/$NCAR_HOST/matlab/$matlab_version

if [[ ! -d $engine_prefix ]]; then
    echo "*** Installing Matlab engine for $NCAR_HOST ***"
    install_engine
else
    echo "Matlab engine exists for $NCAR_HOST; skipping step ..."
fi

# --- CREATE KERNEL LAUNCHER

function create_kernel_launcher {
cat > $1 << EOF
#!/bin/bash

module --force purge
module load ncarenv/\$1 conda matlab/\$2

conda activate $CONDA_PREFIX

engine_path=\$(echo \$CONDA_PREFIX/kernel-packages/\$NCAR_HOST/matlab/\$2/lib/python*/site-packages)
export PYTHONPATH=\$engine_path
export LD_PRELOAD=\$CONDA_PREFIX/lib/libstdc++.so.6
shift; shift

exec python -m matlab_kernel -f \$@
EOF

chmod +x $1
}

if [[ ! -f $CONDA_PREFIX/kernel-launchers/matlab ]]; then
    echo "*** Creating Matlab kernel launcher ***"
    mkdir -p $CONDA_PREFIX/kernel-launchers
    create_kernel_launcher $CONDA_PREFIX/kernel-launchers/matlab
else
    echo "Launcher exists; skipping step ..."
fi

# --- CREATE KERNEL

function create_kernel {
cat > $1 << EOF
{
    "argv": ["$CONDA_PREFIX/kernel-launchers/matlab",
        "$LMOD_FAMILY_ENV_VERSION",
        "$matlab_version",
        "{connection_file}"],
    "display_name": "Matlab $matlab_version${kernel_prefix:+ (${kernel_prefix/-})}",
    "language": "matlab",
    "mimetype": "text/x-octave",
    "name": "$kernel_name"
}
EOF
}

if [[ ! -f $kernel_file ]]; then
    echo "*** Creating kernel file for $matlab_version ***"
    asset_dir=/glade/u/apps/etc/logos/matlab

    if [[ -d $asset_dir ]]; then
        cp -r $asset_dir $hub_kernels_private/$kernel_name
    else
        mkdir -p $hub_kernels_private/$kernel_name
    fi

    create_kernel $kernel_file
else
    echo "Kernel exists; skipping step ..."
fi

# Preserve script
cp $0 $CONDA_PREFIX/ncar
