#!/bin/bash
#
#   This script installs a kernel for a specified version of IDL
#

set -e

# Settings
my_dir="$( cd "$(dirname "$(readlink -f "$0")")" ; pwd )"
my_user=$(whoami)
ncarenv_version=$(module -t list |& grep ncarenv | cut -d/ -f2)
idl_version=$(module -t list |& grep idl | cut -d/ -f2)

if [[ -z $idl_version ]]; then
    >&2 echo "Error: Please load desired IDL module first!"
    exit 1
fi

if [[ " $@ " != *" --user "* ]]; then
    if [[ $my_user != csgteam ]]; then
        export kernel_prefix="ktest-"
    fi

    if [[ $CONDA_PREFIX != *jhk-* ]] && [[ $CONDA_PREFIX != *jhub-* ]]; then
        >&2 echo "Error: Please load a JupyterHub Kernel conda environment first!"
        exit 1
    fi
elif [[ -z $CONDA_PREFIX ]] || ! which jupyter-lab >& /dev/null; then
    >&2 echo "Error: Please load a Conda environment with JupyterLab first!"
    exit 1
else
    export kernel_prefix="user-"
fi

if [[ $my_user == csgteam ]]; then
    export hub_kernels_private=/glade/u/ssg/ch/usr/jupyterhub/kernels
    export hub_kernels_public=/glade/u/apps/jupyterhub/csg-managed/prod/kernels
else
    export hub_kernels_private=$HOME/.local/share/jupyter/kernels
fi

kernel_name=${kernel_prefix}idl-${idl_version,,}
kernel_file=$hub_kernels_private/$kernel_name/kernel.json

module -q purge
module -q load ncarenv/$ncarenv_version idl/$idl_version

# --- CREATE KERNEL LAUNCHER

function create_kernel_launcher {
cat > $1 << EOF
#!/bin/bash

module --force purge
module load ncarenv

if [[ \$NCAR_HOST == cheyenne ]]; then
    module load conda idl/\$2
else
    module load ncarenv/\$1 conda idl/\$2
fi

shift; shift

conda activate $CONDA_PREFIX
export PYTHONPATH=\$NCAR_ROOT_IDL/idl/lib/bridges

exec python -m idl_kernel -f \$@
EOF

chmod +x $1
}

if [[ ! -f $CONDA_PREFIX/kernel-launchers/idl ]]; then
    echo "*** Creating IDL kernel launcher ***"
    mkdir -p $CONDA_PREFIX/kernel-launchers
    create_kernel_launcher $CONDA_PREFIX/kernel-launchers/idl
else
    echo "Launcher exists; skipping step ..."
fi

# --- CREATE KERNEL

function create_kernel {
cat > $1 << EOF
{
    "argv": ["$CONDA_PREFIX/kernel-launchers/idl",
        "$LMOD_FAMILY_ENV_VERSION",
        "$idl_version",
        "{connection_file}"],
    "display_name": "IDL $idl_version${kernel_prefix:+ (${kernel_prefix/-})}",
    "language": "idl",
    "codemirror_mode": "idl",
    "name": "$kernel_name"
}
EOF
}

if [[ ! -f $kernel_file ]]; then
    echo "*** Creating kernel file for $idl_version ***"
    asset_dir=/glade/u/apps/etc/logos/idl

    if [[ -d $asset_dir ]]; then
        cp -r $asset_dir $hub_kernels_private/$kernel_name
    else
        mkdir -p $hub_kernels_private/$kernel_name
    fi

    create_kernel $kernel_file
else
    echo "Kernel exists; skipping step ..."
fi

# Preserve script
cp $0 $CONDA_PREFIX/ncar
